version: "3.3"

services:
    challenge:
        image: challenge-img
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5001:5001
        networks:
            - challenge
        depends_on:
            - mongo
    
    mongo:
        image: mongo
        restart: always
        ports:
            - 10002:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 12345
        networks:
            - challenge
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 10003:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
            ME_CONFIG_MONGODB_URL: mongodb://admin:12345@mongo:27017/
        networks:
            - challenge
            
networks:
    challenge:
        driver: bridge